/**
 * This class is generated by jOOQ
 */
package com.epam.cdp.patterns.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.5.2"
        },
        comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CreditcardRecord extends org.jooq.impl.UpdatableRecordImpl<com.epam.cdp.patterns.db.tables.records.CreditcardRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.math.BigDecimal> {

    private static final long serialVersionUID = -721529042;

    /**
     * Setter for <code>cinema.creditcard.id</code>.
     */
    public void setId(java.lang.Long value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>cinema.creditcard.id</code>.
     */
    public java.lang.Long getId() {
        return (java.lang.Long) getValue(0);
    }

    /**
     * Setter for <code>cinema.creditcard.number</code>.
     */
    public void setNumber(java.lang.String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>cinema.creditcard.number</code>.
     */
    public java.lang.String getNumber() {
        return (java.lang.String) getValue(1);
    }

    /**
     * Setter for <code>cinema.creditcard.balance</code>.
     */
    public void setBalance(java.math.BigDecimal value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>cinema.creditcard.balance</code>.
     */
    public java.math.BigDecimal getBalance() {
        return (java.math.BigDecimal) getValue(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Record1<java.lang.Long> key() {
        return (org.jooq.Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row3<java.lang.Long, java.lang.String, java.math.BigDecimal> fieldsRow() {
        return (org.jooq.Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row3<java.lang.Long, java.lang.String, java.math.BigDecimal> valuesRow() {
        return (org.jooq.Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Long> field1() {
        return com.epam.cdp.patterns.db.tables.Creditcard.CREDITCARD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field2() {
        return com.epam.cdp.patterns.db.tables.Creditcard.CREDITCARD.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.math.BigDecimal> field3() {
        return com.epam.cdp.patterns.db.tables.Creditcard.CREDITCARD.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value2() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.math.BigDecimal value3() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditcardRecord value1(java.lang.Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditcardRecord value2(java.lang.String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditcardRecord value3(java.math.BigDecimal value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditcardRecord values(java.lang.Long value1, java.lang.String value2, java.math.BigDecimal value3) {
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CreditcardRecord
     */
    public CreditcardRecord() {
        super(com.epam.cdp.patterns.db.tables.Creditcard.CREDITCARD);
    }

    /**
     * Create a detached, initialised CreditcardRecord
     */
    public CreditcardRecord(java.lang.Long id, java.lang.String number, java.math.BigDecimal balance) {
        super(com.epam.cdp.patterns.db.tables.Creditcard.CREDITCARD);

        setValue(0, id);
        setValue(1, number);
        setValue(2, balance);
    }
}
