/**
 * This class is generated by jOOQ
 */
package com.epam.cdp.patterns.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.5.2"
        },
        comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class HallRecord extends org.jooq.impl.UpdatableRecordImpl<com.epam.cdp.patterns.db.tables.records.HallRecord> implements org.jooq.Record2<java.lang.Long, java.lang.String> {

    private static final long serialVersionUID = 1751070729;

    /**
     * Setter for <code>cinema.hall.id</code>.
     */
    public void setId(java.lang.Long value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>cinema.hall.id</code>.
     */
    public java.lang.Long getId() {
        return (java.lang.Long) getValue(0);
    }

    /**
     * Setter for <code>cinema.hall.name</code>.
     */
    public void setName(java.lang.String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>cinema.hall.name</code>.
     */
    public java.lang.String getName() {
        return (java.lang.String) getValue(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Record1<java.lang.Long> key() {
        return (org.jooq.Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row2<java.lang.Long, java.lang.String> fieldsRow() {
        return (org.jooq.Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row2<java.lang.Long, java.lang.String> valuesRow() {
        return (org.jooq.Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Long> field1() {
        return com.epam.cdp.patterns.db.tables.Hall.HALL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field2() {
        return com.epam.cdp.patterns.db.tables.Hall.HALL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HallRecord value1(java.lang.Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HallRecord value2(java.lang.String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HallRecord values(java.lang.Long value1, java.lang.String value2) {
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HallRecord
     */
    public HallRecord() {
        super(com.epam.cdp.patterns.db.tables.Hall.HALL);
    }

    /**
     * Create a detached, initialised HallRecord
     */
    public HallRecord(java.lang.Long id, java.lang.String name) {
        super(com.epam.cdp.patterns.db.tables.Hall.HALL);

        setValue(0, id);
        setValue(1, name);
    }
}
