/**
 * This class is generated by jOOQ
 */
package com.epam.cdp.patterns.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.5.2"
        },
        comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlaceRecord extends org.jooq.impl.UpdatableRecordImpl<com.epam.cdp.patterns.db.tables.records.PlaceRecord> implements org.jooq.Record4<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long> {

    private static final long serialVersionUID = -536551159;

    /**
     * Setter for <code>cinema.place.id</code>.
     */
    public void setId(java.lang.Long value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>cinema.place.id</code>.
     */
    public java.lang.Long getId() {
        return (java.lang.Long) getValue(0);
    }

    /**
     * Setter for <code>cinema.place.row</code>.
     */
    public void setRow(java.lang.Integer value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>cinema.place.row</code>.
     */
    public java.lang.Integer getRow() {
        return (java.lang.Integer) getValue(1);
    }

    /**
     * Setter for <code>cinema.place.number</code>.
     */
    public void setNumber(java.lang.Integer value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>cinema.place.number</code>.
     */
    public java.lang.Integer getNumber() {
        return (java.lang.Integer) getValue(2);
    }

    /**
     * Setter for <code>cinema.place.hallId</code>.
     */
    public void setHallid(java.lang.Long value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>cinema.place.hallId</code>.
     */
    public java.lang.Long getHallid() {
        return (java.lang.Long) getValue(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Record1<java.lang.Long> key() {
        return (org.jooq.Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row4<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long> fieldsRow() {
        return (org.jooq.Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row4<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long> valuesRow() {
        return (org.jooq.Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Long> field1() {
        return com.epam.cdp.patterns.db.tables.Place.PLACE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Integer> field2() {
        return com.epam.cdp.patterns.db.tables.Place.PLACE.ROW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Integer> field3() {
        return com.epam.cdp.patterns.db.tables.Place.PLACE.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Long> field4() {
        return com.epam.cdp.patterns.db.tables.Place.PLACE.HALLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Integer value2() {
        return getRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Integer value3() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Long value4() {
        return getHallid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value1(java.lang.Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value2(java.lang.Integer value) {
        setRow(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value3(java.lang.Integer value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value4(java.lang.Long value) {
        setHallid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Long value4) {
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaceRecord
     */
    public PlaceRecord() {
        super(com.epam.cdp.patterns.db.tables.Place.PLACE);
    }

    /**
     * Create a detached, initialised PlaceRecord
     */
    public PlaceRecord(java.lang.Long id, java.lang.Integer row, java.lang.Integer number, java.lang.Long hallid) {
        super(com.epam.cdp.patterns.db.tables.Place.PLACE);

        setValue(0, id);
        setValue(1, row);
        setValue(2, number);
        setValue(3, hallid);
    }
}
