/**
 * This class is generated by jOOQ
 */
package com.epam.cdp.patterns.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.5.2"
        },
        comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<com.epam.cdp.patterns.db.tables.records.UserRecord> implements org.jooq.Record4<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long> {

    private static final long serialVersionUID = -1096206859;

    /**
     * Setter for <code>cinema.user.id</code>.
     */
    public void setId(java.lang.Long value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>cinema.user.id</code>.
     */
    public java.lang.Long getId() {
        return (java.lang.Long) getValue(0);
    }

    /**
     * Setter for <code>cinema.user.username</code>.
     */
    public void setUsername(java.lang.String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>cinema.user.username</code>.
     */
    public java.lang.String getUsername() {
        return (java.lang.String) getValue(1);
    }

    /**
     * Setter for <code>cinema.user.password</code>.
     */
    public void setPassword(java.lang.String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>cinema.user.password</code>.
     */
    public java.lang.String getPassword() {
        return (java.lang.String) getValue(2);
    }

    /**
     * Setter for <code>cinema.user.creditCardId</code>.
     */
    public void setCreditcardid(java.lang.Long value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>cinema.user.creditCardId</code>.
     */
    public java.lang.Long getCreditcardid() {
        return (java.lang.Long) getValue(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Record1<java.lang.Long> key() {
        return (org.jooq.Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row4<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long> fieldsRow() {
        return (org.jooq.Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row4<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long> valuesRow() {
        return (org.jooq.Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Long> field1() {
        return com.epam.cdp.patterns.db.tables.User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field2() {
        return com.epam.cdp.patterns.db.tables.User.USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field3() {
        return com.epam.cdp.patterns.db.tables.User.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Long> field4() {
        return com.epam.cdp.patterns.db.tables.User.USER.CREDITCARDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Long value4() {
        return getCreditcardid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(java.lang.Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(java.lang.String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(java.lang.String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(java.lang.Long value) {
        setCreditcardid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.Long value4) {
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(com.epam.cdp.patterns.db.tables.User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(java.lang.Long id, java.lang.String username, java.lang.String password, java.lang.Long creditcardid) {
        super(com.epam.cdp.patterns.db.tables.User.USER);

        setValue(0, id);
        setValue(1, username);
        setValue(2, password);
        setValue(3, creditcardid);
    }
}
