/**
 * This class is generated by jOOQ
 */
package com.epam.cdp.patterns.db;

/**
 * Convenience access to all tables in cinema
 */
@javax.annotation.Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.5.2"
        },
        comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table cinema.creditcard
     */
    public static final com.epam.cdp.patterns.db.tables.Creditcard CREDITCARD = com.epam.cdp.patterns.db.tables.Creditcard.CREDITCARD;

    /**
     * The table cinema.film
     */
    public static final com.epam.cdp.patterns.db.tables.Film FILM = com.epam.cdp.patterns.db.tables.Film.FILM;

    /**
     * The table cinema.hall
     */
    public static final com.epam.cdp.patterns.db.tables.Hall HALL = com.epam.cdp.patterns.db.tables.Hall.HALL;

    /**
     * The table cinema.order
     */
    public static final com.epam.cdp.patterns.db.tables.Order ORDER = com.epam.cdp.patterns.db.tables.Order.ORDER;

    /**
     * The table cinema.place
     */
    public static final com.epam.cdp.patterns.db.tables.Place PLACE = com.epam.cdp.patterns.db.tables.Place.PLACE;

    /**
     * The table cinema.seance
     */
    public static final com.epam.cdp.patterns.db.tables.Seance SEANCE = com.epam.cdp.patterns.db.tables.Seance.SEANCE;

    /**
     * The table cinema.ticket
     */
    public static final com.epam.cdp.patterns.db.tables.Ticket TICKET = com.epam.cdp.patterns.db.tables.Ticket.TICKET;

    /**
     * The table cinema.user
     */
    public static final com.epam.cdp.patterns.db.tables.User USER = com.epam.cdp.patterns.db.tables.User.USER;
}
